package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Deployment'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Deployment")) {
    dependencies {
        expect(RelativeId("Installer")) {
            snapshot {
                synchronizeRevisions = false
            }

            artifacts {
                artifactRules = "+:installer.txt"
            }
        }
        update(RelativeId("Installer")) {
            snapshot {
            }

            artifacts {
                artifactRules = "+:installer.txt"
            }
        }

    }
}
